name: Create Event Pull Request
on:
  workflow_dispatch:
    inputs:
      committer:
        type: string
        required: true
      email:
        type: string
        required: true
      title:
        type: string
        required: true
      body:
        type: string
        required: true
        
      year:
        type: number
        required: true
      month:
        type: number
        required: true
      day:
        type: number
        required: true
        
      event:
        type: string
        required: true
jobs:
  Create-Event-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Add Event
        run: python cli_db.py push ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} ${{ toJSON(github.event.inputs.event) }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          committer: ${{ github.event.inputs.committer }} <${{ github.event.inputs.email }}>
          commit-message: "[일정 추가] ${{ github.event.inputs.title }}"
          title: "[일정 추가] ${{ github.event.inputs.title }}" 
          body: |-
            ${{ github.event.inputs.body }}

            일정 데이터:
            ````json event_data
            {"committer":${{ github.event.inputs.committer }},"email":${{ github.event.inputs.email }},"year":${{ github.event.inputs.year }},"month":${{ github.event.inputs.month }},"day":${{ github.event.inputs.day }},"event":${{toJSON(github.event.inputs.event)}}}
            ````
          labels: 일정 요청(자동)
          branch: event-request
          branch-suffix: random
          author: ${{ github.event.inputs.committer }} <${{ github.event.inputs.email }}>
          delete-branch: true
