name: Resolve Same Day Conflict
on:
  issue_comment:
    types: [created]
jobs:
  Solve-Conflict:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/resolve_day') && contains(github.event.pull_request.labels.*.name, '일정 요청(자동)')
    steps:
      - name: Remove requested event by resetting to main branch 
        run: git fetch --all && git reset --hard origin/main
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Parse event data from PR body
        uses: peter-murray/issue-body-parse-action@v2
        id: event_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}
          payload_marker: event_data
      - name: Add requested event
        if : steps.event_parser.outputs.payload != 'NOT_FOUND'
        run: python cli_db.py push ${{ fromJSON(steps.event_parser.outputs.payload).year }} ${{ fromJSON(steps.event_parser.outputs.payload).month }} ${{ fromJSON(steps.event_parser.outputs.payload).day }} ${{ fromJSON(steps.event_parser.outputs.payload).event }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "Resolve conflict"
          push: true
